openapi: 3.0.3
info:
  title: Order Service API
  description: |
    Order Service manages the order lifecycle from creation to completion.

    ## Features
    - Create and validate orders
    - Cancel orders with compensation
    - Query orders by status, customer, or ID
    - Trigger Temporal workflows for order fulfillment

    ## Error Handling
    All endpoints return standardized error responses with the following structure:
    ```json
    {
      "code": "ERROR_CODE",
      "message": "Human-readable error message",
      "details": {
        "field": "error description"
      },
      "requestId": "req-123",
      "timestamp": "2025-12-23T10:00:00Z",
      "path": "/api/v1/orders"
    }
    ```
  version: 1.0.0
  contact:
    name: WMS Platform Team
    email: wms-platform@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:8001
    description: Local development server
  - url: https://api-staging.wms.example.com
    description: Staging environment
  - url: https://api.wms.example.com
    description: Production environment

tags:
  - name: orders
    description: Order management endpoints
  - name: health
    description: Health check endpoints

paths:
  /health:
    get:
      tags:
        - health
      summary: Health check
      description: Returns service health status
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  service:
                    type: string
                    example: order-service
                  timestamp:
                    type: string
                    format: date-time

  /ready:
    get:
      tags:
        - health
      summary: Readiness check
      description: Returns service readiness status (checks MongoDB connection)
      operationId: readinessCheck
      responses:
        '200':
          description: Service is ready
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ready
                  service:
                    type: string
                    example: order-service
        '503':
          description: Service is not ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /metrics:
    get:
      tags:
        - health
      summary: Prometheus metrics
      description: Returns Prometheus metrics
      operationId: getMetrics
      responses:
        '200':
          description: Metrics in Prometheus format
          content:
            text/plain:
              schema:
                type: string

  /api/v1/orders:
    post:
      tags:
        - orders
      summary: Create a new order
      description: |
        Creates a new order and starts the Temporal OrderFulfillment workflow.

        The order will be validated, assigned to a wave, and processed through
        the complete fulfillment pipeline.
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      tags:
        - orders
      summary: List orders
      description: |
        Returns a paginated list of orders with optional filters.

        Supports filtering by:
        - Customer ID
        - Status
        - Priority
      operationId: listOrders
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/PageSizeParam'
        - name: customerId
          in: query
          description: Filter by customer ID
          schema:
            type: string
        - name: status
          in: query
          description: Filter by order status
          schema:
            type: string
            enum: [received, validated, wave_assigned, picking, picked, consolidating, packing, packed, shipping, shipped, completed, cancelled]
        - name: priority
          in: query
          description: Filter by priority
          schema:
            type: string
            enum: [same_day, next_day, standard]
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/orders/{orderId}:
    get:
      tags:
        - orders
      summary: Get order by ID
      description: Returns a single order by its unique identifier
      operationId: getOrder
      parameters:
        - name: orderId
          in: path
          required: true
          description: Order identifier
          schema:
            type: string
            example: ORD-a1b2c3d4
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/orders/{orderId}/validate:
    put:
      tags:
        - orders
      summary: Validate order
      description: |
        Validates an order and publishes OrderValidated event.

        Validation includes:
        - Customer exists
        - Items are valid
        - Inventory available
        - Address is deliverable
      operationId: validateOrder
      parameters:
        - name: orderId
          in: path
          required: true
          description: Order identifier
          schema:
            type: string
      responses:
        '200':
          description: Order validated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/orders/{orderId}/cancel:
    put:
      tags:
        - orders
      summary: Cancel order
      description: |
        Cancels an order with compensation logic.

        Compensation includes:
        - Release reserved inventory
        - Remove from wave (if assigned)
        - Cancel picking task (if started)
        - Notify customer
      operationId: cancelOrder
      parameters:
        - name: orderId
          in: path
          required: true
          description: Order identifier
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelOrderRequest'
      responses:
        '200':
          description: Order cancelled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Cannot cancel order in current status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/orders/status/{status}:
    get:
      tags:
        - orders
      summary: List orders by status
      description: Returns a paginated list of orders filtered by status
      operationId: listOrdersByStatus
      parameters:
        - name: status
          in: path
          required: true
          description: Order status
          schema:
            type: string
            enum: [received, validated, wave_assigned, picking, picked, consolidating, packing, packed, shipping, shipped, completed, cancelled]
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/PageSizeParam'
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListResponse'

  /api/v1/orders/customer/{customerId}:
    get:
      tags:
        - orders
      summary: List orders by customer
      description: Returns a paginated list of orders for a specific customer
      operationId: listOrdersByCustomer
      parameters:
        - name: customerId
          in: path
          required: true
          description: Customer identifier
          schema:
            type: string
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/PageSizeParam'
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListResponse'

components:
  parameters:
    PageParam:
      name: page
      in: query
      description: Page number (1-indexed)
      schema:
        type: integer
        minimum: 1
        default: 1
    PageSizeParam:
      name: pageSize
      in: query
      description: Number of items per page
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20

  schemas:
    CreateOrderRequest:
      type: object
      required:
        - customerId
        - items
        - shippingAddress
        - priority
        - promisedDeliveryAt
      properties:
        customerId:
          type: string
          description: Customer unique identifier
          example: CUST-123
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderItemRequest'
        shippingAddress:
          $ref: '#/components/schemas/AddressRequest'
        priority:
          type: string
          enum: [same_day, next_day, standard]
          description: Order priority level
          example: same_day
        promisedDeliveryAt:
          type: string
          format: date-time
          description: Promised delivery date and time
          example: '2025-12-25T15:00:00Z'

    OrderItemRequest:
      type: object
      required:
        - sku
        - quantity
        - weight
      properties:
        sku:
          type: string
          description: Stock keeping unit
          example: SKU-12345
        quantity:
          type: integer
          minimum: 1
          description: Quantity ordered
          example: 2
        weight:
          type: number
          format: float
          minimum: 0
          description: Item weight in kilograms
          example: 1.5

    AddressRequest:
      type: object
      required:
        - street
        - city
        - state
        - postalCode
        - country
      properties:
        street:
          type: string
          example: 123 Main St
        city:
          type: string
          example: San Francisco
        state:
          type: string
          minLength: 2
          maxLength: 2
          example: CA
        postalCode:
          type: string
          example: '94105'
        country:
          type: string
          minLength: 2
          maxLength: 2
          example: US

    CancelOrderRequest:
      type: object
      required:
        - reason
      properties:
        reason:
          type: string
          minLength: 3
          maxLength: 500
          description: Reason for cancellation
          example: Customer requested cancellation

    OrderResponse:
      type: object
      properties:
        orderId:
          type: string
          example: ORD-a1b2c3d4
        customerId:
          type: string
          example: CUST-123
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemResponse'
        shippingAddress:
          $ref: '#/components/schemas/AddressResponse'
        priority:
          type: string
          enum: [same_day, next_day, standard]
          example: same_day
        status:
          type: string
          enum: [received, validated, wave_assigned, picking, picked, consolidating, packing, packed, shipping, shipped, completed, cancelled]
          example: received
        promisedDeliveryAt:
          type: string
          format: date-time
          example: '2025-12-25T15:00:00Z'
        createdAt:
          type: string
          format: date-time
          example: '2025-12-23T10:00:00Z'
        updatedAt:
          type: string
          format: date-time
          example: '2025-12-23T10:00:00Z'

    OrderItemResponse:
      type: object
      properties:
        sku:
          type: string
          example: SKU-12345
        quantity:
          type: integer
          example: 2
        weight:
          type: number
          format: float
          example: 1.5

    AddressResponse:
      type: object
      properties:
        street:
          type: string
          example: 123 Main St
        city:
          type: string
          example: San Francisco
        state:
          type: string
          example: CA
        postalCode:
          type: string
          example: '94105'
        country:
          type: string
          example: US

    OrderListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/OrderResponse'
        page:
          type: integer
          example: 1
        pageSize:
          type: integer
          example: 20
        totalItems:
          type: integer
          example: 100
        totalPages:
          type: integer
          example: 5
        hasNext:
          type: boolean
          example: true
        hasPrev:
          type: boolean
          example: false

    Error:
      type: object
      properties:
        code:
          type: string
          description: Machine-readable error code
          example: VALIDATION_ERROR
        message:
          type: string
          description: Human-readable error message
          example: Invalid order data
        details:
          type: object
          additionalProperties:
            type: string
          description: Additional error details
          example:
            orderId: required
            customerId: invalid format
        requestId:
          type: string
          description: Request identifier for tracing
          example: req-123
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
          example: '2025-12-23T10:00:00Z'
        path:
          type: string
          description: Request path
          example: /api/v1/orders
