---
# PostgreSQL for Temporal
apiVersion: v1
kind: Service
metadata:
  name: temporal-postgresql
  namespace: wms-platform
  labels:
    app: temporal-postgresql
spec:
  ports:
    - port: 5432
      name: postgresql
  selector:
    app: temporal-postgresql
---
apiVersion: v1
kind: Secret
metadata:
  name: temporal-postgresql
  namespace: wms-platform
type: Opaque
stringData:
  postgresql-password: temporal123
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temporal-postgresql-data
  namespace: wms-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-postgresql
  namespace: wms-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-postgresql
  template:
    metadata:
      labels:
        app: temporal-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: temporal-postgresql
                  key: postgresql-password
            - name: POSTGRES_DB
              value: temporal
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: temporal-postgresql-data
