---
# Kafka Connect Cluster for Debezium CDC
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: wms-kafka-connect
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.0.0
  replicas: 1
  bootstrapServers: wms-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
  image: docker.io/library/wms-kafka-connect-debezium:v1
  config:
    group.id: wms-connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    offset.storage.replication.factor: 1
    config.storage.replication.factor: 1
    status.storage.replication.factor: 1
    # Converters for CloudEvents compatibility
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    # Config providers for secrets
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
  jvmOptions:
    -Xms: "256m"
    -Xmx: "512m"
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  template:
    pod:
      volumes:
        - name: mongodb-credentials
          secret:
            secretName: mongodb-credentials-debezium
    connectContainer:
      volumeMounts:
        - name: mongodb-credentials
          mountPath: /mnt/secrets/mongodb-credentials
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: connect-metrics
        key: metrics-config.yml
---
# Metrics ConfigMap for Kafka Connect
apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-metrics
  namespace: kafka
data:
  metrics-config.yml: |
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
    - pattern: "kafka.connect<type=connect-worker-metrics>([^:]+):"
      name: "kafka_connect_worker_$1"
    - pattern: "kafka.connect<type=connector-metrics, connector=([^,]+)><>([^:]+)"
      name: "kafka_connect_connector_$2"
      labels:
        connector: "$1"
    - pattern: "kafka.connect<type=task-metrics, connector=([^,]+), task=([^,]+)><>([^:]+)"
      name: "kafka_connect_task_$3"
      labels:
        connector: "$1"
        task: "$2"
    - pattern: "debezium.([^:]+)<type=connector-metrics, context=([^,]+), server=([^,]+)><>([^:]+)"
      name: "debezium_$1_$4"
      labels:
        context: "$2"
        server: "$3"
